language: node_js
node_js:
  - "8"
  - "10"
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov

jobs:
  include:
    - stage: release
      nodejs: 12
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
